/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;
import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author n0516005
 */

/*
Name: public class Chat extends Menu
Description:
Chat is the human interface for sending and receiveing messages, 
displaying friends and other people that are online. In Chat the functions
below send a request based on the users action. If the user wanted to send
a message, they twould have to type in the recipients username and then it would
privately send. All messages can be viewed within the one menu.

Chat class Extends Menu to load the screen.

CurrentUser is retrieved from the profile that is logged in.
This is used to send requests to the server so the server knows who
is sending the requests.

*/
public class Chat extends Menu
{
    //ArrayList<String> friends;
    String CurrentUser;
    //private JButton add, remove;
   // private boolean waitingForLocationClick;
    
    /**
     * Creates new form chat
     */
    
    
    
    /*
    Chat Constructor: Chat(ScreenManager screen)
    Description:
    Chat Constructor calls the super Class to load the screen
    Then Initialises the menu GUI components.
    */
    public Chat(ScreenManager screen)
    {
        super(screen);
        initComponents();
        
    }
    
    /*
    Name: Initialise
    Description:
    set the CurrenUser to the current profiles username that are logged in.
    */
    public void Initialise()
    {
       CurrentUser = screenManager.profile.currentUser();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FriendChatx = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatWall = new javax.swing.JTextArea();
        messageBox = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        SendMessage = new javax.swing.JButton();
        messageTo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PopulateFriends = new javax.swing.JButton();
        CloseChat = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        OnlineUsersList = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        FriendsList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chatWall.setColumns(20);
        chatWall.setRows(5);
        jScrollPane1.setViewportView(chatWall);

        SendMessage.setText("Send");
        SendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendMessageActionPerformed(evt);
            }
        });

        jLabel1.setText("To:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(messageBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageTo, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageTo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(messageBox)
                    .addComponent(SendMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addContainerGap())
        );

        FriendChatx.addTab("Chat to Friends", jPanel1);

        PopulateFriends.setText("Click to update friends lists");
        PopulateFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopulateFriendsActionPerformed(evt);
            }
        });

        CloseChat.setText("Close Chat");
        CloseChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseChatActionPerformed(evt);
            }
        });

        OnlineUsersList.setColumns(20);
        OnlineUsersList.setRows(5);
        jScrollPane2.setViewportView(OnlineUsersList);

        jTabbedPane1.addTab("Online Users", jScrollPane2);

        FriendsList.setColumns(20);
        FriendsList.setRows(5);
        jScrollPane3.setViewportView(FriendsList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Friends", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(FriendChatx)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(CloseChat))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PopulateFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(FriendChatx))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CloseChat)
                        .addGap(11, 11, 11)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PopulateFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addContainerGap())
        );

        FriendChatx.getAccessibleContext().setAccessibleName("Friend");
        FriendChatx.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /*
    Name: addMessage
    Description.
    Add a message to the chat wall by appending it to the JTextArea
    */
    public void addMessage(String message)
    {
        chatWall.append(message);
    }
    
     /*
    Name: SendMessageActionPerformed
    Description.
    When the Send message button has been pressed, the chat wall will appened
    the users username to the wall (Who is sending the message) seperate the 
    message from the senders name then add the message (Taken from the messageBox
    component.):
    
    chatWall.append(CurrentUser + ": " + messageBox.getText() + "\n")
    
    package the sender, message and reciever (reciever taken from the messageTo 
    JTextFeild) into an array. 
    
    String[] myMessage = new String[3];
    myMessage[0] = messageTo.getText();
    myMessage[1] = screenManager.profile.currentUser();
    myMessage[2] = messageBox.getText();
    
    send a request to the server to chat followed by the array containing the
    source username, message, and destination username.
    
    screenManager.clientServer.netIO.sendRequest("Chat", myMessage)
    */
    private void SendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendMessageActionPerformed
        chatWall.append(CurrentUser + ": " + messageBox.getText() + "\n");
        String[] myMessage = new String[3];
        myMessage[0] = messageTo.getText();
        myMessage[1] = screenManager.profile.currentUser();
        myMessage[2] = messageBox.getText();
        try
        {
            screenManager.clientServer.netIO.sendRequest("Chat", myMessage);
        }
        catch (IOException ex)
        {
            Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
        }
        messageBox.setText("");
        
    }//GEN-LAST:event_SendMessageActionPerformed

    // Send request to populate JTextAreas (FriendsList, OnlineUsersList) with friends and 
    //Online people respectively.
    private void PopulateFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopulateFriendsActionPerformed
        try
        {
            screenManager.clientServer.netIO.sendRequest("GetFriends", CurrentUser);
            screenManager.clientServer.netIO.sendRequest("activeUsers", "");
        }
        catch (IOException ex)
        {
            Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PopulateFriendsActionPerformed
    
    //search through friends array, append friends to Array "Friends"
    //display in JTextArea FriendsList.
    public void updateFriends(String[] Friends)
    {
        String friend = "";
        
        for (String Friend : Friends) {
            friend += (Friend + "\n"); 
        }
        FriendsList.setText(friend);
    }
    
    public void Clear()
    {
        messageBox.setText("");
        chatWall.setText("");
        FriendsList.setText("");
        OnlineUsersList.setText("");
    }
    
    //search through "People" array, append friend to OnlineUsersList.
    //display in JTextArea OnlineUsersList.
    public void updateActive(String[] People)
    {
        String people = "";
        
        for (String Person : People) {
            people += (Person + "\n"); 
        }
        OnlineUsersList.setText(people);
    }
    //Close the chat window by setting its visibility to false.
    private void CloseChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseChatActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CloseChatActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseChat;
    private javax.swing.JTabbedPane FriendChatx;
    private javax.swing.JTextArea FriendsList;
    private javax.swing.JTextArea OnlineUsersList;
    private javax.swing.JButton PopulateFriends;
    private javax.swing.JButton SendMessage;
    private javax.swing.JTextArea chatWall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField messageBox;
    private javax.swing.JTextField messageTo;
    // End of variables declaration//GEN-END:variables
}

