/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;

/**
 *
 * @author n0516005
 */

/*
Name: Wall
Description:

*/


public class Wall extends Menu {
    
    ArrayList<String> wallData;
    /**
     * Creates new form Wall
     */
    
    //Constructor set screen using Super class, initialise GUI components
    //define and initialise Wall array to empty strings per index.
    public Wall(ScreenManager screen)
    {
        super(screen);
        initComponents();
        wallData = new ArrayList();
        wallData.add("");
        wallData.add("");
        wallData.add("");
        wallData.add("");
        wallData.add("");
    }
    
    //when initialising the wall, the getProfile Function is called to populate 
    //the profile infomration with the loggin in users data.
    //Set the Text of the users username on the profile and set the editable state of the
    //wall to false, this stops the user from writing in the notifcations window.

    public void Initialise()
    {
        //add a wait function
        super.Initialise();
        
        screenManager.profile.getProfile();    
        
        profileName.setText(screenManager.profile.currentUser());
        WallText.setEditable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        MyProfileTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        profileName = new javax.swing.JLabel();
        ProfilePicture = new javax.swing.JLabel();
        ProfileFirstAndSecondName = new javax.swing.JLabel();
        ProfileGender = new javax.swing.JLabel();
        ProfileDOB = new javax.swing.JLabel();
        FeedWall = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        WallText = new javax.swing.JTextArea();
        InterestsLabel = new javax.swing.JLabel();
        ProfileInterests = new javax.swing.JLabel();
        workLabel = new javax.swing.JLabel();
        ProfileWork = new javax.swing.JLabel();
        workLabel1 = new javax.swing.JLabel();
        ProfileEducation = new javax.swing.JLabel();
        residanceLabel = new javax.swing.JLabel();
        ProfileResidance = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        OpenChat = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        Settings = new javax.swing.JButton();
        SearchBar = new javax.swing.JTextField();
        SearchForFriends = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        profileName.setText("Profile user Name");

        ProfilePicture.setText("place profile picture here");

        ProfileFirstAndSecondName.setText("Profile full name");

        ProfileGender.setText("ProfileGender");

        ProfileDOB.setText("yyyy-mm-dd");

        FeedWall.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        WallText.setColumns(20);
        WallText.setRows(5);
        jScrollPane2.setViewportView(WallText);

        javax.swing.GroupLayout FeedWallLayout = new javax.swing.GroupLayout(FeedWall);
        FeedWall.setLayout(FeedWallLayout);
        FeedWallLayout.setHorizontalGroup(
            FeedWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedWallLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        FeedWallLayout.setVerticalGroup(
            FeedWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedWallLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        InterestsLabel.setText("Interests:");

        ProfileInterests.setText("Interests go here.....\\n");
        ProfileInterests.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        workLabel.setText("Work:");

        ProfileWork.setText("Work goes here");

        workLabel1.setText("School/ College:");

        ProfileEducation.setText("Education Goes here.....");

        residanceLabel.setText("Lives at:");

        ProfileResidance.setText("Where do you live?.........");

        jLabel1.setText("Username:");

        jLabel2.setText("Full name:");

        jLabel3.setText("DOB:");

        jLabel4.setText("Gender");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ProfilePicture)
                        .addComponent(InterestsLabel)
                        .addComponent(workLabel1)
                        .addComponent(ProfileEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(residanceLabel)
                        .addComponent(ProfileResidance)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(workLabel)
                            .addGap(20, 20, 20)
                            .addComponent(ProfileWork))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ProfileFirstAndSecondName)
                                .addComponent(profileName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ProfileDOB)
                                .addComponent(ProfileGender))))
                    .addComponent(ProfileInterests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(FeedWall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(ProfilePicture)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profileName)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfileFirstAndSecondName)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfileDOB)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfileGender)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19)
                .addComponent(InterestsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfileInterests, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfileWork)
                    .addComponent(workLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(workLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfileEducation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(residanceLabel)
                .addGap(18, 18, 18)
                .addComponent(ProfileResidance)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FeedWall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MyProfileTab.addTab("My Profile", jPanel1);

        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        OpenChat.setText("Open Chat");
        OpenChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenChatActionPerformed(evt);
            }
        });

        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        Settings.setText("Settings");
        Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsActionPerformed(evt);
            }
        });

        SearchForFriends.setText("Add Friend");
        SearchForFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchForFriendsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(OpenChat))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SearchBar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchForFriends)
                                .addGap(58, 58, 58)
                                .addComponent(RefreshButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Settings)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Logout))
                            .addComponent(MyProfileTab)
                            .addComponent(jSeparator1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logout)
                    .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchForFriends)
                    .addComponent(Settings, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyProfileTab, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(OpenChat)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //open the chat window
    private void OpenChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenChatActionPerformed
        //screenManager.setScreen("Chat");
        screenManager.openChat();
        
    }//GEN-LAST:event_OpenChatActionPerformed
    //Refresh button is pressed therefore...
    //Get the current user from Profile class (See Profile class for details)
    //set the profile information fields to the appropriate index
    //Request sent to server for getting friends requests.
    
    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        String username = screenManager.profile.currentUser();
        
        profileName.setText(username); // change the way chat is called.
        String[] profileInfo = screenManager.profile.getFullProfile();
        ProfileFirstAndSecondName.setText(profileInfo[0] + " " + profileInfo[1]);
        ProfileDOB.setText(profileInfo[2]);
        ProfileGender.setText(profileInfo[3]);
        ProfileInterests.setText(profileInfo[4]);
        ProfileWork.setText(profileInfo[5]);
        ProfileEducation.setText(profileInfo[6]);
        ProfileResidance.setText(profileInfo[7]);
        
        try
        {
            //update friend request
            screenManager.clientServer.netIO.sendRequest("GetFriendsReq", username);
        }
        catch (IOException ex)
        {
            Logger.getLogger(Wall.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RefreshButtonActionPerformed
    
    
    public void PrintList(String[] List)
    {
        String wallString = "";
        for (String wallData1 : List)
            wallString += wallData1 + " Wants to be your friend! Type in their name to accept.\n";
        WallText.setText(wallString);
    }
            
    
    
    private void SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsActionPerformed
        screenManager.setScreen("ProfileEdit");
    }//GEN-LAST:event_SettingsActionPerformed

    public void updateFeed(String update)
    {
        wallData.add(update);
        wallData.remove(0);
        String wallString = "";
        for (String WallData1 : wallData)
        {
            wallString += WallData1 + "\n";
        }
        WallText.setText(wallString);
    }
    
    private void SearchForFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchForFriendsActionPerformed
        // search for user in all users
        String myUser, friendUser;
        myUser = screenManager.profile.currentUser();
        friendUser = SearchBar.getText();
        String[] sendDetails = new String[2];
        sendDetails[0] = myUser;
        sendDetails[1] = friendUser;
        try
        {
            screenManager.clientServer.netIO.sendRequest("FriendRequest", sendDetails);
        }
        catch (IOException ex)
        {
            Logger.getLogger(Wall.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_SearchForFriendsActionPerformed
    //Clear chat and send request to logout.
    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        
        
        try
        {
            screenManager.chatMenu.Clear();
            screenManager.clientServer.netIO.sendRequest("Logout", "");
        }
        catch (IOException ex)
        {
            Logger.getLogger(Wall.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_LogoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FeedWall;
    private javax.swing.JLabel InterestsLabel;
    private javax.swing.JButton Logout;
    private javax.swing.JTabbedPane MyProfileTab;
    private javax.swing.JButton OpenChat;
    private javax.swing.JLabel ProfileDOB;
    private javax.swing.JLabel ProfileEducation;
    private javax.swing.JLabel ProfileFirstAndSecondName;
    private javax.swing.JLabel ProfileGender;
    private javax.swing.JLabel ProfileInterests;
    private javax.swing.JLabel ProfilePicture;
    private javax.swing.JLabel ProfileResidance;
    private javax.swing.JLabel ProfileWork;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JButton SearchForFriends;
    private javax.swing.JButton Settings;
    private javax.swing.JTextArea WallText;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel profileName;
    private javax.swing.JLabel residanceLabel;
    private javax.swing.JLabel workLabel;
    private javax.swing.JLabel workLabel1;
    // End of variables declaration//GEN-END:variables
}
